version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: peroperje/circleci-test-setup_app
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -f Dockerfile.prod -t $IMAGE_NAME:latest .

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - staging
